from jinja2 import Template
from datetime import date

brief_template = Template("""
# {{ title }}
**Date:** {{ today }}

**Category:** {{ category }}
**Impact:** {{ impact }}

**Recommended Actions**
{% for a in actions -%}
- {{ a }}
{% endfor %}

---
*Generated by Nexora Intelligence Engine*
""")

def render_brief(event):
    return brief_template.render(
        title=event.get("title","Event Brief"),
        today=date.today(),
        category=event.get("category"),
        impact=event.get("impact"),
        actions=event.get("actions",[])
    )
